# Generated by Django 3.1.1 on 2021-01-17 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='MenuSpecimen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=512, null=True, verbose_name='Состав')),
                ('cost', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Цена')),
                ('weight', models.CharField(blank=True, max_length=16, null=True, verbose_name='Вес (в граммах)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu', verbose_name='Изображение')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='main.menucategory', verbose_name='Тип')),
                ('specimen', models.ManyToManyField(related_name='specimen', to='main.MenuSpecimen', verbose_name='Меню')),
            ],
        ),
    ]
