# Generated by Django 3.1.1 on 2020-11-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200929_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='weight',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
