# Generated by Django 3.1.1 on 2020-11-09 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201108_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='cost',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='kind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kind', to='main.menukind'),
        ),
    ]
